### PR TITLE
Disable the default monitoring custom configuration values

### PR DESCRIPTION
**Pull request by scalar-boney**
Current Scalar DL Ledger and Auditor deployment guide do not support Scalar DL specific monitoring services. We will create a monitoring guide soon.

If these values are true, we need to create a namespace and deploy Prometheus.

### CODE REVIEW

**Comment by miseyu** [comment]
Was monitoring enabled by default in the first place?
I think it depends on that background story.

**Comment by scalar-boney** [comment]
> Was monitoring enabled by default in the first place? I think it depends on that background story.

@feeblefakie san,
Do we need to keep it enabled?
I think we have 2 options, use the cloud monitor service and use Prometheus and Grafana.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by miseyu — APPROVED** [review]
LGTM

**Pull request merged**
