### PR TITLE
Add a script file to update chart docs

### PR DESCRIPTION
**Pull request by superbrothers**
This commit adds `update-chart-docs.sh` that updates README.md for each
Helm charts and `verify-chart-docs.sh` that checks if README.md needs to
be updated. `verify-chart-docs.sh` can be run in CI to prevent
forgetting to update README.md.

---

This PR is based on #92. Please review and merge it first.

### CODE REVIEW

**Review by ymorimo — APPROVED** [review]
LGTM! Good enhancement for CI.
Sorry for the late review.

**Review by feeblefakie — APPROVED** [review]
LGMT! Thank you!

**Comment by feeblefakie** [comment]
@superbrothers Can you resolve the conflicts?
please use ghcr.io for the registry.

**Comment by superbrothers** [comment]
I've rebased this PR from the master branch.

**Pull request merged**
