### PR TITLE
Separate helm charts

### PR DESCRIPTION
**Pull request by tei-k**
# Description
https://scalar-labs.atlassian.net/browse/DLT-8785

# Done
- Delete `charts` directory
- Delete workflow of `charts`
- Fix to getting [charts](https://github.com/scalar-labs/helm-charts) from github.
- Refactoring config path

# Remark
Maybe we can publish charts to Github pages and use `community.kubernetes.helm` to install helm charts in next.

### CODE REVIEW

**Comment by superbrothers** [comment]
I feel that the commits in this PR need to be tidied up. At least https://github.com/scalar-labs/scalar-kubernetes/pull/116/commits/13e986337eacd8ff28bfd8c66ff5f8d2714b586e is an unnecessary commit.

**Comment by feeblefakie** [comment]
@superbrothers We will squash multiple commits into one commit so 13e9863 won't be separately committed into a main. (so 1 PR creates 1 commit in main)
Do you mean we should divide the PR into multiple PRs?

**Review by ymorimo — APPROVED** [review]
Looks good! But the deployment with Ansible is a bit complicated. As you mentioned, it would be nice if we release the charts to the own Helm repo on GitHub Pages so that we don't have to install git with Ansible.

**Comment by superbrothers** [comment]
> Do you mean we should divide the PR into multiple PRs?

@feeblefakie No, that wasn't my intention, I didn't understand the rule about not rebasing from main after creating a PR. I also understood that commits would eventually be squashed. I have no problem with that! :bow:

**Comment by tei-k** [comment]
> it would be nice if we release the charts to the own Helm repo on GitHub Pages so that we don't have to install git with Ansible.

@ymorimo Thanks! I'll to do it in the next step.

**Review by superbrothers — APPROVED** [review]

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
