### PR TITLE
Fix to use kube prometheus stack

### PR DESCRIPTION
**Pull request by tei-k**
# Description
https://scalar-labs.atlassian.net/browse/DLT-8829

[stable/prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) has been deprecated.

# Done
Fix to use [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

### CODE REVIEW

**Comment by feeblefakie** [comment]
@tei-k Sorry, but @superbrothers can't see the story in Jira, so can you explain what this PR is and why this is for?

**Comment by tei-k** [comment]
>but @superbrothers can't see the story in Jira, so can you explain what this PR is and why this is for?

Oh! sorry! added to description.

**Comment by ymorimo** [comment]
@tei-k I faced another problem.

```console
$ ansible-playbook -i ${SCALAR_K8S_CONFIG_DIR}/inventory.ini playbooks/playbook-deploy-prometheus.yml
...
TASK [prometheus : Install Helm Diff] *********************************************************************************************************************************************************
fatal: [bastion-1-ym-test-0ezymxy.westus2.cloudapp.azure.com]: FAILED! => {"changed": false, "command": "/usr/local/bin/helm plugin install https://github.com/databus23/helm-diff", "msg": "Failure when executing Helm command.", "rc": 1, "stderr": "Error: git is not installed\n", "stderr_lines": ["Error: git is not installed"], "stdout": "", "stdout_lines": []}
```

It's needed to install Git on the bastion manually with `yum`.  It might not be related to this PR, but shouldn't it be automated with Ansible?

**Comment by tei-k** [comment]
>It's needed to install Git on the bastion manually with yum. It might not be related to this PR, but shouldn't it be automated with Ansible?

@ymorimo 
`git` will be installed by the `sclardl` role now.
https://github.com/scalar-labs/scalar-kubernetes/blob/master/playbooks/roles/scalardl/tasks/install.yml

I'll check it again.

I plan to move the `git` installation to `playbook-install-tools.yml`
https://github.com/scalar-labs/scalar-kubernetes/pull/121/files#diff-635e86041499390a21001dac612d5e61899a28da08066e4f26d5880cbc450579

**Comment by ymorimo** [comment]
> `git` will be installed by the `sclardl` role now.

@tei-k I see that I didn't have `git` on the bastion since I used `helm` to deploy Scalar DL. Nice to hear that the Git installation is going to be moved to the right place.

**Review by ymorimo — APPROVED** [review]
LGTM!

**Review by feeblefakie — APPROVED** [review]
LGTM!

**Review by superbrothers — APPROVED** [review]

**Pull request merged**
